# Generated by Django 4.2.3 on 2023-07-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storestatus',
            unique_together={('store', 'time_stamp_utc')},
        ),
    ]
