# Generated by Django 4.2.3 on 2023-07-29 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_storestatus_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uptime_last_week', models.CharField(max_length=100)),
                ('downtime_last_week', models.CharField(max_length=100)),
                ('uptime_last_day', models.CharField(max_length=100)),
                ('downtime_last_day', models.CharField(max_length=100)),
                ('uptime_last_hour', models.CharField(max_length=100)),
                ('downtime_last_hour', models.CharField(max_length=100)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.timezone')),
            ],
        ),
    ]
